title: MQTT CLI
description: A feature-rich MQTT Command line interface
logo: assets/images/02-mqtt-cli-neg.svg
version: 4.4.0

remote_theme: SgtSilvio/just-the-docs@3e0de1c7
color_scheme: dark

permalink: pretty

collections:
  docs:
    output: true

just_the_docs:
  collections:
    html_pages:
    docs:
  github:
    repo_link:
      enabled: true
    edit_link:
      enabled: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: false
  button: true

aux_links:
  "News":
    - "https://hivemq.github.io/mqtt-cli/news"

plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: false
  collections: true

relative_links:
  enabled: true
  collections: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [ ]
  blanklines: false
  profile: false