name: acceptance-tests-secondary-parallel
on:
  push:
    branches: [ uyuni ]










jobs:
  test-uyuni:
    uses: ./.github/workflows/acceptance_tests_common.yml
    strategy:
      fail-fast: false
      matrix:
        set: ['1', '2', '3', '4', '5']
    with:
      secondary_tests: "18_run_secondary_parallelizable_tests_subset.sh ${{ matrix.set }}"
