name: Publish

on:
  push:
    branches: [ mqtt-cli ]







jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Publish
        run: ./gradlew githubRelease gitPublishPush jib
        env:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
