name: Run Snyk monitor on releases

on:
  push:
    branches: [ mqtt-cli ]



jobs:
  run-snyk-monitor:
    runs-on: ubuntu-latest
    environment: snyk-monitor-releases

    steps:
      - uses: actions/checkout@v3
        with:
          path: mqtt-cli

      - name: Run Snyk monitor
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --configuration-matching=^runtimeClasspath$ --target-reference=${{ github.ref_name }} mqtt-cli
